name: CI
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 17

    - run: npm install
    - run: npm run build
    - run: npm run coverage
    - run: cp -rp coverage/lcov-report build/
    
    - name: Create Coverage Badges
      uses: jaywcjlove/coverage-badges-cli@main
      with:
        output: build/badges.svg

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        output: build/CONTRIBUTORS.svg
        avatarSize: 42

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
